# Generated by Django 3.0.3 on 2020-05-16 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
